# Site settings
title: ahmed gado
author: Ahmed Gado
email: ahmed.gado@tufts.edu
description: > # this means to ignore newlines until "twitter_username:"
    Personal engineering blog

# social links
github_username: upgado
twitter_username: gadoplus
linkedin_username: gadoahmed
youtube_username: GadoDesigns

show_excerpts: false

plugins:
    - jekyll-remote-theme
    - jekyll-seo-tag
    - jemoji
    - jekyll-sitemap
    - jekyll-time-to-read

remote_theme: jekyll/minima
