# Site settings
title: Ahmed Gado
author: Ahmed Gado
email: ahmed.gado@tufts.edu
description: > # this means to ignore newlines until "twitter_username:"
    Ahmed Gado's website

# social links
github_username: upgado
facebook_username: ahmedehabg
linkedin_username: gadoahmed
youtube_username: GadoDesigns

show_excerpts: false

plugins:
    - jekyll-remote-theme

remote_theme: jekyll/minima
