# Site settings
title: dio gado
email: dio@upgado.com

# social links
github_username: upgado
twitter_username: upgado
linkedin_username: gadoahmed

show_excerpts: false

plugins:
    - jekyll-remote-theme
    - jekyll-seo-tag
    - jemoji
    - jekyll-sitemap
    - jekyll-time-to-read

theme: minima
baseurl: "upgado.github.io"
